server:
  port: 8830
  
logging:
    file: dajiaoyun-community-demo.log  
    
spring:
  application:
      name: dajiaoyun-community-demo
  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always